# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [30]:
import numpy as np
arr = np.arange(1,11)
print(arr)
arr

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [31]:
zero_mat = np.zeros((3,3))
zero_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [32]:
spaced_mat = np.linspace(0, 5, 10)
spaced_mat

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [39]:
id_mat = np.eye((5,5))
id_mat

TypeError: 'tuple' object cannot be interpreted as an integer


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [42]:
np.random.seed(0)

In [44]:
rand = np.random.random((4,4))
rand

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

---

### Exercise 6:
Find the shape of a NumPy array.


In [35]:
np.shape(rand)

(4, 4)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [36]:
arr2 = np.linspace(1,5,16)
reshaped_mat = arr2.reshape((4,4))
reshaped_mat

array([[1.        , 1.26666667, 1.53333333, 1.8       ],
       [2.06666667, 2.33333333, 2.6       , 2.86666667],
       [3.13333333, 3.4       , 3.66666667, 3.93333333],
       [4.2       , 4.46666667, 4.73333333, 5.        ]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.



In [37]:
reshaped_mat.dtype

dtype('float64')


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [46]:
print([x for x in np.arange(1,101) if x%2==0])

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]




---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [58]:
np.random.randint(10,51,(6,6))

array([[38, 44, 10, 10, 46, 15],
       [48, 50, 27, 25, 14, 41],
       [11, 11, 49, 45, 48, 21],
       [28, 37, 10, 24, 45, 22],
       [30, 21, 14, 16, 14, 13],
       [22, 46, 50, 24, 25, 30]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [69]:
mat = np.random.randint(1,5,(2,5))
mat


array([[2, 3, 2, 1, 3],
       [3, 4, 1, 4, 3]])

In [72]:
mat[:,2:]

array([[2, 1, 3],
       [1, 4, 3]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [95]:
arr3 = np.random.randint(1,51,100)
arr3

array([46,  8, 40, 22, 34, 45, 35, 35, 25, 34,  6, 41, 37,  1, 12, 35,  6,
       17,  9,  2, 18, 49, 36, 28, 41, 37, 49, 26,  4, 40, 36, 31, 30, 50,
       34, 19, 18, 30, 21,  3,  6, 38, 13, 45,  3, 48, 28, 22, 40, 40, 12,
       23, 31, 18,  7,  8, 19, 29, 44, 20, 50, 42, 30, 47, 22, 10, 26, 33,
       28, 10, 29, 44, 18, 42,  1, 23, 17, 43, 37, 31, 25,  4,  9, 28, 30,
       47, 24, 33, 20,  9,  8, 24, 14, 18,  1, 12, 29, 37, 26, 33])

In [96]:
arr3.sum()

2598


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [97]:
arr3.mean()

25.98

In [98]:
arr3.std()

13.789836837323348

In [99]:
np.median(arr3)

28.0



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [100]:
arr3.min()

1

In [101]:
arr3.max()

50


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [114]:
arr4 = np.random.randint(1,100,20)
arr4

array([92, 44, 64, 32, 21, 71, 10, 61, 92, 36, 84, 77, 19, 75, 99, 98, 44,
        4, 13, 59])

In [117]:
print("The index of", arr4.max(), "is", np.argmax(arr4))

The index of 99 is 14


In [124]:
import time 
s = time.time()
np.where(arr4==arr4.max())
t = time.time() -s 
t

0.00035119056701660156

In [125]:
s = time.time()
np.argmax(arr4)
t = time.time() -s 
t

5.507469177246094e-05


---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [118]:
np.flip(arr4)

array([59, 13,  4, 44, 98, 99, 75, 19, 77, 84, 36, 92, 61, 10, 71, 21, 32,
       64, 44, 92])

In [126]:
s = time.time()
np.flip(arr4)
t = time.time() -s 
t

8.153915405273438e-05

In [120]:
arr4[::-1]

array([59, 13,  4, 44, 98, 99, 75, 19, 77, 84, 36, 92, 61, 10, 71, 21, 32,
       64, 44, 92])

In [127]:
s = time.time()
arr4[::-1]
t = time.time() -s 
t

4.57763671875e-05


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [128]:
arr5 = np.random.randint(1,10,(3,3))
print(arr5)
arr6 = np.random.randint(1,10,(3,3))
print(arr6)

[[2 2 1]
 [8 9 5]
 [4 6 7]]
[[4 3 9]
 [2 5 1]
 [9 4 6]]


In [129]:
arr5 * arr6

array([[ 8,  6,  9],
       [16, 45,  5],
       [36, 24, 42]])


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [151]:
arr7 = np.random.randint(-5,5,5)
arr7

array([ 3,  1, -1,  1, -2])

In [154]:
np.diag(arr7)

array([[ 3,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0, -1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, -2]])


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [160]:
arr8 = np.random.randint(1,10,(2,2))
print(arr8)
arr9 = np.random.randint(1,10,(2,2))
print(arr9)

[[6 4]
 [3 4]]
[[3 6]
 [5 2]]


In [161]:
np.multiply(arr8,arr9)

array([[18, 24],
       [15,  8]])


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [162]:
arr8

array([[6, 4],
       [3, 4]])

In [163]:
np.ravel(arr8)

array([6, 4, 3, 4])


---

### Exercise 21:
Stack two NumPy arrays vertically.


In [167]:
arr5, arr6

(array([[2, 2, 1],
        [8, 9, 5],
        [4, 6, 7]]),
 array([[4, 3, 9],
        [2, 5, 1],
        [9, 4, 6]]))

In [169]:
np.concatenate((arr5,arr6), axis=1)

array([[2, 2, 1, 4, 3, 9],
       [8, 9, 5, 2, 5, 1],
       [4, 6, 7, 9, 4, 6]])


---

### Exercise 22:
Stack two NumPy arrays horizontally.

In [170]:
np.concatenate((arr5,arr6), axis=0)

array([[2, 2, 1],
       [8, 9, 5],
       [4, 6, 7],
       [4, 3, 9],
       [2, 5, 1],
       [9, 4, 6]])


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [173]:
arr10 = np.random.randint(1,10,(7,7))
arr10

array([[8, 5, 1, 3, 7, 3, 5],
       [6, 5, 5, 9, 2, 6, 8],
       [1, 2, 4, 3, 9, 3, 5],
       [9, 3, 9, 8, 9, 3, 4],
       [4, 7, 1, 4, 7, 4, 7],
       [4, 3, 3, 3, 7, 5, 7],
       [1, 5, 3, 2, 7, 2, 8]])

In [176]:
np.array_split(arr10, 5)

[array([[8, 5, 1, 3, 7, 3, 5],
        [6, 5, 5, 9, 2, 6, 8]]),
 array([[1, 2, 4, 3, 9, 3, 5],
        [9, 3, 9, 8, 9, 3, 4]]),
 array([[4, 7, 1, 4, 7, 4, 7]]),
 array([[4, 3, 3, 3, 7, 5, 7]]),
 array([[1, 5, 3, 2, 7, 2, 8]])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [185]:
arr11 = np.random.random(10)
np.round(arr11.reshape(2,5), 2)

array([[0.33, 0.79, 0.1 , 0.44, 0.52],
       [0.69, 0.09, 0.23, 0.41, 0.62]])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [215]:
arr12 = np.random.randint(1,10,20)
arr12

array([2, 1, 9, 8, 8, 1, 5, 9, 1, 5, 6, 8, 3, 5, 8, 6, 1, 5, 5, 1])

In [216]:
np.unique(arr12)

array([1, 2, 3, 5, 6, 8, 9])

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [223]:
arr13 = np.where(arr12<=3,4,arr12)
arr13

array([4, 4, 9, 8, 8, 4, 5, 9, 4, 5, 6, 8, 4, 5, 8, 6, 4, 5, 5, 4])


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [227]:
sum(arr13), sum(arr11)

4.230233850972477


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [243]:
arr14 = np.random.randint(-2,2,20)
arr14

array([-2, -2,  1, -2,  0, -1,  1,  0, -1,  0,  1, -1, -1, -2,  0,  0, -1,
        0, -1, -1])

In [244]:
np.count_nonzero(arr14)

14


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [253]:
arr15 = np.random.randint(1,20,20)
arr15

array([ 3, 11, 13, 18,  8, 17, 11,  3, 16, 12, 15, 10,  4, 17,  1, 14,  7,
        5,  4, 18])

In [254]:
np.sort(arr15)

array([ 1,  3,  3,  4,  4,  5,  7,  8, 10, 11, 11, 12, 13, 14, 15, 16, 17,
       17, 18, 18])


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [256]:
arr6

array([[4, 3, 9],
       [2, 5, 1],
       [9, 4, 6]])

In [260]:
np.sum(arr6, axis=1) # row-wise sum

array([16,  8, 19])

In [261]:
np.sum(arr6, axis=0) # column-wise sum

array([15, 12, 16])


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---
